# Generated by Django 4.1.5 on 2023-08-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamourApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, default='Default Color', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, default='Default Size', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='color',
            field=models.CharField(blank=True, default='Default Color', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, default='Default Size', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(default='Default Color', related_name='products', to='glamourApp.productcolor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(default='Default Size', related_name='products', to='glamourApp.productsize'),
        ),
    ]
