# Generated by Django 4.1.5 on 2023-08-25 05:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('glamourApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.AddField(
            model_name='review',
            name='authorEmail',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='review',
            name='authorFullName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='review',
            name='authorPhoneNumber',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='review',
            name='ratings',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authorFullName', models.CharField(default='', max_length=255)),
                ('authorEmail', models.CharField(default='', max_length=255)),
                ('authorPhoneNumber', models.CharField(default='', max_length=255)),
                ('comment', models.TextField(default='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='glamourApp.product')),
            ],
        ),
    ]
