# Generated by Django 4.2.4 on 2023-09-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamourApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(default='', related_name='products', to='glamourApp.productcolor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(default='', related_name='products', to='glamourApp.productsize'),
        ),
    ]
