# Generated by Django 4.1.5 on 2023-08-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamourApp', '0003_alter_productsize_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(related_name='products', to='glamourApp.productsize'),
        ),
    ]
