# Generated by Django 4.1.5 on 2023-08-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glamourApp', '0004_newslettersubscribers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
