# Generated by Django 4.1.5 on 2023-08-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamourApp', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REPORTS', 'Reports'), ('FINANCE', 'Finance'), ('ALERT', 'Alert'), ('REGISTRATION', 'Registration'), ('ORDER', 'Order'), ('MESSAGE', 'Message')], default='Reports', max_length=255),
        ),
    ]
