# Generated by Django 4.1.5 on 2023-08-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamourApp', '0009_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REPORTS', 'Reports'), ('FINANCE', 'Finance'), ('ALERT', 'Alert'), ('REGISTRATION', 'Registration'), ('ORDER', 'Order'), ('ACTIVITY', 'Activity')], default='Reports', max_length=255),
        ),
    ]
