# Generated by Django 4.1.5 on 2023-08-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamourApp', '0012_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
    ]
