# Generated by Django 4.1.5 on 2023-08-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamourApp', '0013_cartitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='', max_length=10),
        ),
    ]
