# Generated by Django 4.1.5 on 2023-08-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamourApp', '0014_cartitem_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order_number',
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
